### ISSUE TITLE
Finish wireframe design

### ISSUE THREAD

**Issue by JackCSheehan** [acm-projects/Focus-Browser#16]
Planned date to finish design and begin implementation of application: Saturday, February 29th. Design should be completed by beginning of meeting, with some general possible finalization happening during the meeting.

#### Tasks
* [x] - Finish basic browser outline
* [x] - Finish pull-out menu design
* [x] - Settings page design

**Comment by JackCSheehan** [comment]
Planned date to finish design and begin implementation of application: Saturday, February 29th. Design should be completed by beginning of meeting, with some general possible finalization happening during the meeting.
